### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by dextronomous** [cosmoio/bitcoin_key_recovery#1]
could you help me out on how to start your file.
i could not make it out.

**Comment by cosmoio** [comment]
You need a wordlist (single column) and the bitcoin explorer bx utility (https://github.com/libbitcoin/libbitcoin-explorer/wiki). The chances that you will crack anything with this tool are slim to none though! I hacked this together in an hour or so .. 
If you need to recover some data I suggest giving hashcat a try.
